[project]
name = "third"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.10.0",
    "juniper>=0.5.5",
    "numpy>=2.4.2",
    "torch>=2.10.0",
]

[tool.pyright]
reportUnknownMemberType=false
